name: MOPH Archive

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      # You can use PyPy versions in python-version. For example, pypy2 and pypy3
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.x
    #- name: Install pdfbox
    #  run: sudo apt-get install -y libpdfbox-java
    # You can test your matrix by printing the current Python version
    - name: PDF to Text
      run: |
        pip install -r requirements.txt
        python build.py
    - name: Clean text
      run: python clean.py
    - uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Apply thai-covid-19 changes
        branch: ${{ github.head_ref }}
